updated the workflow

diff --git a/.github/workflows/jfrog.yml b/.github/workflows/jfrog.yml
--- a/.github/workflows/jfrog.yml
+++ b/.github/workflows/jfrog.yml
@@ -40,15 +40,16 @@ jobs:
         run: |
           jf audit --watches "demo" 
       
-      - name: Check JFrog Scan Results
-        run: |
-          if grep -qE "Found [1-9][0-9]* IaC vulnerabilities" <<< "${{ steps.jfrog-scan.outputs.stdout }}"; then
-            echo "Found IaC vulnerabilities. Stopping Terraform plan."
-            exit 1
-          else
-            echo "No non-zero IaC vulnerabilities found. Proceeding with Terraform plan."
-          fi
+      # - name: Check JFrog Scan Results
+      #   run: |
+      #     if grep -qE "Found [1-9][0-9]* IaC vulnerabilities" <<< "${{ steps.jfrog-scan.outputs.stdout }}"; then
+      #       echo "Found IaC vulnerabilities. Stopping Terraform plan."
+      #       exit 1
+      #     else
+      #       echo "No non-zero IaC vulnerabilities found. Proceeding with Terraform plan."
+      #     fi
 
       - name: Plan Terraform
+        if: failure()
         run: terraform plan 
 
